version: '3.9'
services:
  voters-api:
    container_name: ngr27-voters-api
    image: ngregrichardson/voters-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '1081:1081'
    networks:
      - ngr27
    environment:
      - VISIBLE_API_HOST=localhost
      - POLLS_API_URL = http://localhost:1080
networks:
  ngr27:
    external: true
    
