version: '3.9'
services:
  redis:
    container_name: ngr27-redis
    image: 'redis/redis-stack:latest'
    ports:
      - '8001:8001'
      - '6379:6379'
    networks:
      - ngr27
networks:
  ngr27:
    driver: bridge
    name: ngr27