version: '3.9'
services:
  polls-api:
    container_name: ngr27-polls-api
    image: ngregrichardson/polls-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '1080:1080'
    networks:
      - ngr27
    environment:
      - VISIBLE_API_HOST=localhost
networks:
  ngr27:
    external: true
    
